### PR TITLE
Fixed problem with "tab+shift,tab" triggering on shift. 

### PR DESCRIPTION
**Pull request by NigelThorne**
Also only triggers callback once if matched.
- Treat everything as combo - this simplifies some code. ( I don't know the performance impacts)
- Fix regex to pass "+" as part of name for splitting later. ("tab+shift,tab" was firing on just "shift")
- Only trigger a single callback once if more than one combo for the same callback matches. It calls the callback with the first matching key combination... so "tab+shift,tab" will match tab+shift in preference. The body can then check for  the actual combination... key==="tab+shift" or key==="tab".

Note:  "tab,tab+shift" will only ever call with "tab" as it is a subset and gets checked first.

### CODE REVIEW

**Comment by dsteppeler** [comment]
I think I have almost the same problem. I added 

``` javascript
$(document).jkey('alt+shift+f',function() {
      customFunction();
});
```

The first time it is triggered correctly on "alt+shift+f". But after that "alt+shift" will also trigger the function. For testing I added another key ("alt+shift+f+u"). The same effect: first time the function triggers on "alt+shift+f+u" as expected. After that it will trigger in "alt+shift+f".

So it seems that after the first time usage of the key code the last key in the chain gets lost.

In order to be complete: I have another key code on "alt+s" which works fine and doesn't have the same effect. The problem occurs on latest Firefox, Mac OSX Mavericks.

**Comment by NigelThorne** [comment]
Try my fork. See if it works.

**Comment by dsteppeler** [comment]
It did not work for me, the problem remains.

**Comment by NigelThorne** [comment]
try now.

**Comment by dsteppeler** [comment]
Unfortunately it still doesn't work.
I was trying to use this key code combination in order to activate/deactivate fullscreen mode in browser. I also tested if "alt+shift" causes the browser to exit fullscreen mode even if the key code is deactivated, but it doesn't. So it seems to be a problem of the script.

**Pull request closed without merging**
